### ISSUE TITLE
Discord link

### ISSUE THREAD

**Issue by zaneshaw** [LeonardSSH/LeonardSSH#2]
Discord profile links only open the user's profile modal if the user that opened it is either their friend, or apart of the same server as them. Otherwise it just opens discord and that's it. Idk what you would replace it with, but I just thought it was worth you knowing about.

**Comment by leonardssh** [comment]
Indeed, discord doesn't have a special link to be redirected to a specific profile. I'll see what I can replace it with, maybe just a discord tag or something. Thanks!
